#pragma once
#include "predefines.hpp"
enum class Result
{
	SUCCEED,
	ERROR_OPEN_FILE,
	ERROR_READING_FILE,
};
enum class ArchiveType
{
	DIRECTORY,
	ZIP,
};
enum class RenderPassType
{
	BACKGROUND, // no depth
	FORWARD,	// 1 color attachments, 1 depth stencil attachment
	DEFERRED,
	// DEFERRED_GEOMETRY,
	// DEFERRED_SHADING,
	ALPHA_TEST,
	SHADOW,
	Num,
};
enum class RenderPath
{
	FORWARD,	// 1 color attachments, 1 depth stencil attachment
	DEFERRED,
};
enum class RenderQueueType
{
	BACKGROUND,
	GEOMETRY,
	ALPHATEST,
	OVERLAY,
	Num
};
enum class MovableObjectType
{
	MESHVIEW,
	CAMERA,
};

enum class MaterialType
{
	UNLIT_COLOR,
	PBR,
	SKYBOX,
	GPASS,
	DEFERRED,
	SHADOW,
	Num
};

// not used
enum class RenderMode
{
	OPAQUE,
	CUTOFF,
	FADE,
	TRANSPARENT,
};


enum class ResourceType
{
	IMAGE,
	MODEL,
	SHADER,
};

enum class TextureInterpolation
{
	LINEAR,	 // mag min are liear, mipmap is nearest
	NEAREST, // nearest
	CUBIC,	 // linear
};

enum class DataType
{
	INT8,
	UINT8,
	INT16,
	UINT16,
	INT32,
	UINT32,
	INT64,
	UINT64,
	FLOAT,
	DOUBLE,

	BVEC2,
	BVEC3,
	BVEC4,
	IVEC2,
	IVEC3,
	IVEC4,
	VEC2,
	VEC3,
	VEC4,
	DVEC2,
	DVEC3,
	DVEC4,

	MAT2,
	MAT2x3,
	MAT2x4,
	MAT3x2,
	MAT3,
	MAT3x4,
	MAT4,
	MAT4x2,
	MAT4x3,
	DMAT2,
	DMAT2x3,
	DMAT2x4,
	DMAT3x2,
	DMAT3,
	DMAT3x4,
	DMAT4,
	DMAT4x2,
	DMAT4x3,

	INT8_NORM,
	UINT8_NORM,
};
enum GLSLUniformType
{
	GLSL_UNIFORM_TYPE_SAMPLER1D,
	GLSL_UNIFORM_TYPE_SAMPLER1DSHADOW,
	GLSL_UNIFORM_TYPE_SAMPLER1DARRAY,
	GLSL_UNIFORM_TYPE_SAMPLER1DARRAYSHADOW,
	GLSL_UNIFORM_TYPE_ISAMPLER1D,
	GLSL_UNIFORM_TYPE_ISAMPLER1DARRAY,
	GLSL_UNIFORM_TYPE_USAMPLER1D,
	GLSL_UNIFORM_TYPE_USAMPLER1DARRAY,
	GLSL_UNIFORM_TYPE_SAMPLER2D,
	GLSL_UNIFORM_TYPE_SAMPLER2DSHADOW,
	GLSL_UNIFORM_TYPE_SAMPLER2DARRAY,
	GLSL_UNIFORM_TYPE_SAMPLER2DARRAYSHADOW,
	GLSL_UNIFORM_TYPE_ISAMPLER2D,
	GLSL_UNIFORM_TYPE_ISAMPLER2DARRAY,
	GLSL_UNIFORM_TYPE_USAMPLER2D,
	GLSL_UNIFORM_TYPE_USAMPLER2DARRAY,
	GLSL_UNIFORM_TYPE_SAMPLER2DRECT,
	GLSL_UNIFORM_TYPE_SAMPLER2DRECTSHADOW,
	GLSL_UNIFORM_TYPE_ISAMPLER2DRECT,
	GLSL_UNIFORM_TYPE_USAMPLER2DRECT,
	GLSL_UNIFORM_TYPE_SAMPLER2DMS,
	GLSL_UNIFORM_TYPE_ISAMPLER2DMS,
	GLSL_UNIFORM_TYPE_USAMPLER2DMS,
	GLSL_UNIFORM_TYPE_SAMPLER2DMSARRAY,
	GLSL_UNIFORM_TYPE_ISAMPLER2DMSARRAY,
	GLSL_UNIFORM_TYPE_USAMPLER2DMSARRAY,
	GLSL_UNIFORM_TYPE_SAMPLER3D,
	GLSL_UNIFORM_TYPE_ISAMPLER3D,
	GLSL_UNIFORM_TYPE_USAMPLER3D,
	GLSL_UNIFORM_TYPE_SAMPLERCUBE,
	GLSL_UNIFORM_TYPE_SAMPLERCUBESHADOW,
	GLSL_UNIFORM_TYPE_ISAMPLERCUBE,
	GLSL_UNIFORM_TYPE_USAMPLERCUBE,
	GLSL_UNIFORM_TYPE_SAMPLERCUBEARRAY,
	GLSL_UNIFORM_TYPE_SAMPLERCUBEARRAYSHADOW,
	GLSL_UNIFORM_TYPE_ISAMPLERCUBEARRAY,
	GLSL_UNIFORM_TYPE_USAMPLERCUBEARRAY,
	GLSL_UNIFORM_TYPE_SAMPLERBUFFER,
	GLSL_UNIFORM_TYPE_ISAMPLERBUFFER,
	GLSL_UNIFORM_TYPE_USAMPLERBUFFER,

	GLSL_UNIFORM_TYPE_IMAGE1D,
	GLSL_UNIFORM_TYPE_IIMAGE1D,
	GLSL_UNIFORM_TYPE_UIMAGE1D,
	GLSL_UNIFORM_TYPE_IMAGE1DARRAY,
	GLSL_UNIFORM_TYPE_IIMAGE1DARRAY,
	GLSL_UNIFORM_TYPE_UIMAGE1DARRAY,
	GLSL_UNIFORM_TYPE_IMAGE2D,
	GLSL_UNIFORM_TYPE_IIMAGE2D,
	GLSL_UNIFORM_TYPE_UIMAGE2D,
	GLSL_UNIFORM_TYPE_IMAGE2DARRAY,
	GLSL_UNIFORM_TYPE_IIMAGE2DARRAY,
	GLSL_UNIFORM_TYPE_UIMAGE2DARRAY,
	GLSL_UNIFORM_TYPE_IMAGE2DRECT,
	GLSL_UNIFORM_TYPE_IIMAGE2DRECT,
	GLSL_UNIFORM_TYPE_UIMAGE2DRECT,
	GLSL_UNIFORM_TYPE_IMAGE2DMS,
	GLSL_UNIFORM_TYPE_IIMAGE2DMS,
	GLSL_UNIFORM_TYPE_UIMAGE2DMS,
	GLSL_UNIFORM_TYPE_IMAGE2DMSARRAY,
	GLSL_UNIFORM_TYPE_IIMAGE2DMSARRAY,
	GLSL_UNIFORM_TYPE_UIMAGE2DMSARRAY,
	GLSL_UNIFORM_TYPE_IMAGE3D,
	GLSL_UNIFORM_TYPE_IIMAGE3D,
	GLSL_UNIFORM_TYPE_UIMAGE3D,
	GLSL_UNIFORM_TYPE_IMAGECUBE,
	GLSL_UNIFORM_TYPE_IIMAGECUBE,
	GLSL_UNIFORM_TYPE_UIMAGECUBE,
	GLSL_UNIFORM_TYPE_IMAGECUBEARRAY,
	GLSL_UNIFORM_TYPE_IIMAGECUBEARRAY,
	GLSL_UNIFORM_TYPE_UIMAGECUBEARRAY,
	GLSL_UNIFORM_TYPE_IMAGEBUFFER,
	GLSL_UNIFORM_TYPE_IIMAGEBUFFER,
	GLSL_UNIFORM_TYPE_UIMAGEBUFFER,

	// vulkan
	GLSL_UNIFORM_TYPE_TEXTURE1D,
	GLSL_UNIFORM_TYPE_TEXTURE1DARRAY,
	GLSL_UNIFORM_TYPE_ITEXTURE1D,
	GLSL_UNIFORM_TYPE_ITEXTURE1DARRAY,
	GLSL_UNIFORM_TYPE_UTEXTURE1D,
	GLSL_UNIFORM_TYPE_UTEXTURE1DARRAY,
	GLSL_UNIFORM_TYPE_TEXTURE2D,
	GLSL_UNIFORM_TYPE_TEXTURE2DARRAY,
	GLSL_UNIFORM_TYPE_ITEXTURE2D,
	GLSL_UNIFORM_TYPE_ITEXTURE2DARRAY,
	GLSL_UNIFORM_TYPE_UTEXTURE2D,
	GLSL_UNIFORM_TYPE_UTEXTURE2DARRAY,
	GLSL_UNIFORM_TYPE_TEXTURE2DRECT,
	GLSL_UNIFORM_TYPE_ITEXTURE2DRECT,
	GLSL_UNIFORM_TYPE_UTEXTURE2DRECT,
	GLSL_UNIFORM_TYPE_TEXTURE2DMS,
	GLSL_UNIFORM_TYPE_ITEXTURE2DMS,
	GLSL_UNIFORM_TYPE_UTEXTURE2DMS,
	GLSL_UNIFORM_TYPE_TEXTURE2DMSARRAY,
	GLSL_UNIFORM_TYPE_ITEXTURE2DMSARRAY,
	GLSL_UNIFORM_TYPE_UTEXTURE2DMSARRAY,
	GLSL_UNIFORM_TYPE_TEXTURE3D,
	GLSL_UNIFORM_TYPE_ITEXTURE3D,
	GLSL_UNIFORM_TYPE_UTEXTURE3D,
	GLSL_UNIFORM_TYPE_TEXTURECUBE,
	GLSL_UNIFORM_TYPE_ITEXTURECUBE,
	GLSL_UNIFORM_TYPE_UTEXTURECUBE,
	GLSL_UNIFORM_TYPE_TEXTURECUBEARRAY,
	GLSL_UNIFORM_TYPE_ITEXTURECUBEARRAY,
	GLSL_UNIFORM_TYPE_UTEXTURECUBEARRAY,
	GLSL_UNIFORM_TYPE_TEXTUREBUFFER,
	GLSL_UNIFORM_TYPE_ITEXTUREBUFFER,
	GLSL_UNIFORM_TYPE_UTEXTUREBUFFER,
	GLSL_UNIFORM_TYPE_SAMPLER,
	GLSL_UNIFORM_TYPE_SAMPLERSHADOW,

	//GLSL_UNIFORM_TYPE_STRUCT,
	GLSL_UNIFORM_TYPE_Num,
};